### ISSUE TITLE
Textures in tyrannosaurus.lua

### ISSUE THREAD

**Issue by daytonnvpaul** [ElCeejoYT/paleotest#1]
Seems as if "textures = textures_awake" isn't loading the proper textures.

**Comment by ElCeejoYT** [comment]
Unfortunately I had to remove that. If I made them load their sleeping textures I would need to use "self.object:set_properties" which makes animations stop playing for some reason.

**Comment by daytonnvpaul** [comment]
Maybe a little more information on my part can describe the issue with more clarity.
tyrannasurus.lua is the only mob having this code. Its also the only mob that has broken/missing textures.

77	     textures = textures_awake,
78	     child_texture = {
79     {"paleotest_tyrannosaurus3.png"},

Changing this section to the same format as the other mobs fixes the broken/missing textures


--      textures = textures_awake,
        textures = {
                {"paleotest_tyrannosaurus1.png"},
                {"paleotest_tyrannosaurus2.png"},
